# Generated by Django 3.2.7 on 2023-09-29 06:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(re.compile('\n                ^[A-Z]\\d$     # строка типа D5, L3 (первая заглавная буква латиницы, вторая цифра)\n                |^[A-Z]{2}$   # ИЛИ строка типа DD, LS, XX (ровно две заглавные буквы латиницы)\n                |\\d{2}        # ИЛИ строка типа 55, 11, 17 (ровно две цифры)\n                ', 64), code='invalid_model', message='Invalid model name')]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(re.compile('\n                ^[A-Z]\\d$     # строка типа D5, L3 (первая заглавная буква латиницы, вторая цифра)\n                |^[A-Z]{2}$   # ИЛИ строка типа DD, LS, XX (ровно две заглавные буквы латиницы)\n                |\\d{2}        # ИЛИ строка типа 55, 11, 17 (ровно две цифры)\n                ', 64), code='invalid_version', message='Invalid version name')]),
        ),
    ]
